version: 2
updates:
  - package-ecosystem: "terraform"
    directories:
      - "**/*"
    schedule:
      # Check for updates to GitHub Actions every day
      interval: "daily"
      time: "10:00"
      timezone: "Australia/Sydney"
